---
- hosts: all
  sudo: true
  vars:
    app_root: /vagrant
    sys_packages: []
    php_packages: ["php5-cli","php5-mcrypt"]
    php_ppa: php5-oldstable
  roles:
    - init
    - mysql
    - phpcommon
    - composer
